[pytest]
asyncio_mode = auto
testpaths =
    shared/tests
    restaurant_service/tests
    rewards_service/tests
    notification_service/tests
    tests
norecursedirs = .venv .git
addopts =
    --cov=.
    --cov-report=xml:coverage.xml
    --cov-report=term-missing
    --cov-fail-under=85
    -v
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
